#log setting
logging:
  level:
    com:
      USWRandomChat:
        backend: info

#email url
email:
  config:
    baseUrl: "http://43.202.91.160:8080"

spring:
  config:
    activate:
      on-profile: prod

  redis:
    host: 0.0.0.0
    port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.202.91.160:3306/swChat?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: swchat
    password: 1234

  thymeleaf:
    cache: false

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true